#Simulation Configuration
#Thu Apr 23 19:16:43 GMT+07:00 2026
individual.ai.on=true
individual.chance=1.0
individual.lifespan=15
individual.period=1
individual.priority.ai=8
legal.ai.on=true
legal.chance=1.0
legal.lifespan=28
legal.period=1
legal.priority.ai=2
show.info.state=true
show.time.state=true
