#Simulation Configuration
#Thu Apr 23 21:47:20 GMT+07:00 2026
individual.ai.on=true
individual.chance=1.0
individual.lifespan=5
individual.period=1
individual.priority.ai=10
legal.ai.on=true
legal.chance=1.0
legal.lifespan=5
legal.period=1
legal.priority.ai=1
show.info.state=true
show.time.state=true
